name: Deploy to EC2 on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

# permissions:
#   contents: write
#   pull-requests: write

jobs:

  build:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: benjaminade/static-site:pr-${{ github.event.number }}

  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$EC2_SSH_KEY" > key.pem
        chmod 400 key.pem
        
        ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
          docker pull benjaminade/static-site:pr-${{ github.event.number }}
          docker stop static-site-${{ github.event.number }} || true
          docker rm static-site-${{ github.event.number }} || true
          docker run -d -p 80:80 --name static-site-${{ github.event.number }} benjaminade/static-site:pr-${{ github.event.number }}
        EOF

    # - name: Comment on PR
    #   uses: peter-evans/commit-comment@v2
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     body: "Deployed pull request to http://${{ secrets.EC2_HOST }}. Container name: static-site-${{ github.event.number }}"
    #     repository: ${{ github.repository }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest

